/*
-- Query: SELECT * FROM `vote-so`.candidate
LIMIT 0, 1000

-- Date: 2022-02-13 19:57
*/
INSERT INTO `vote-so`.`candidate` (`name`,`desc`,`pictureName`) VALUES ('Said Abdullahi Dani','Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi dolor lectus, tristique ut purus nec, consequat viverra lectus. Sed quis ultrices nunc. Nam aliquet molestie neque ac faucibus.','candidate1.jpg');
INSERT INTO `vote-so`.`candidate` (`name`,`desc`,`pictureName`) VALUES ('Hassan Sheikh Momahud','Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi dolor lectus, tristique ut purus nec, consequat viverra lectus. Sed quis ultrices nunc. Nam aliquet molestie neque ac faucibus.','candidate2.jpg');
INSERT INTO `vote-so`.`candidate` (`name`,`desc`,`pictureName`) VALUES ('Hassan Ali Khaire','Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi dolor lectus, tristique ut purus nec, consequat viverra lectus. Sed quis ultrices nunc. Nam aliquet molestie neque ac faucibus.','candidate3.jpg');
INSERT INTO `vote-so`.`candidate` (`name`,`desc`,`pictureName`) VALUES ('Abdirahman Abdishakuur Warsame','Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi dolor lectus, tristique ut purus nec, consequat viverra lectus. Sed quis ultrices nunc. Nam aliquet molestie neque ac faucibus.','candidate4.jpg');
INSERT INTO `vote-so`.`candidate` (`name`,`desc`,`pictureName`) VALUES ('Mustaf Sh. Cali Dhuxulow','Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi dolor lectus, tristique ut purus nec, consequat viverra lectus. Sed quis ultrices nunc. Nam aliquet molestie neque ac faucibus.','candidate5.jpg');
INSERT INTO `vote-so`.`candidate` (`name`,`desc`,`pictureName`) VALUES ('Fawzia Yusuf H. Adam','Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi dolor lectus, tristique ut purus nec, consequat viverra lectus. Sed quis ultrices nunc. Nam aliquet molestie neque ac faucibus.','candidate6.jpg');
INSERT INTO `vote-so`.`candidate` (`name`,`desc`,`pictureName`) VALUES ('Mohamed Abirahman Siiriin','Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi dolor lectus, tristique ut purus nec, consequat viverra lectus. Sed quis ultrices nunc. Nam aliquet molestie neque ac faucibus.','candidate7.jpg');
INSERT INTO `vote-so`.`candidate` (`name`,`desc`,`pictureName`) VALUES ('Mohamed Abdullahi Farmaajo','Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi dolor lectus, tristique ut purus nec, consequat viverra lectus. Sed quis ultrices nunc. Nam aliquet molestie neque ac faucibus.','candidate8.jpg');
INSERT INTO `vote-so`.`candidate` (`name`,`desc`,`pictureName`) VALUES ('Dahir Mohmud Gelle','Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi dolor lectus, tristique ut purus nec, consequat viverra lectus. Sed quis ultrices nunc. Nam aliquet molestie neque ac faucibus.','candidate9.jpg');
INSERT INTO `vote-so`.`candidate` (`name`,`desc`,`pictureName`) VALUES ('Abdinasir Abdille Mohamed','Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi dolor lectus, tristique ut purus nec, consequat viverra lectus. Sed quis ultrices nunc. Nam aliquet molestie neque ac faucibus.','candidate10.jpg');
INSERT INTO `vote-so`.`candidate` (`name`,`desc`,`pictureName`) VALUES ('Abdulkadir Ali Cosoble','Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi dolor lectus, tristique ut purus nec, consequat viverra lectus. Sed quis ultrices nunc. Nam aliquet molestie neque ac faucibus.','candidate11.jpg');
INSERT INTO `vote-so`.`candidate` (`name`,`desc`,`pictureName`) VALUES ('Sheikh Sharif Sheik Ahmed','Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi dolor lectus, tristique ut purus nec, consequat viverra lectus. Sed quis ultrices nunc. Nam aliquet molestie neque ac faucibus.','candidate12.jpg');
INSERT INTO `vote-so`.`candidate` (`name`,`desc`,`pictureName`) VALUES ('Abdikarim Hussein Guuleed','Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi dolor lectus, tristique ut purus nec, consequat viverra lectus. Sed quis ultrices nunc. Nam aliquet molestie neque ac faucibus.','candidate13.jpg');
INSERT INTO `vote-so`.`candidate` (`name`,`desc`,`pictureName`) VALUES ('Hussien Abdi Halane','Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi dolor lectus, tristique ut purus nec, consequat viverra lectus. Sed quis ultrices nunc. Nam aliquet molestie neque ac faucibus.','candidate14.jpg');


INSERT INTO `vote-so`.`votes` (`voter_name`, `voter_email`, `voter_gender`, `voter_age`, `voter_phone`, `candidate_id`, `voter_comment`) VALUES ('Waris', 'abc1@gmail.com', 'Male', '25', '103312005331', '13', 'Very good');
INSERT INTO `vote-so`.`votes` (`voter_name`, `voter_email`, `voter_gender`, `voter_age`, `voter_phone`, `candidate_id`, `voter_comment`) VALUES ('Waris', 'abc2@gmail.com', 'Male', '25', '023312005331', '14', 'Very good');
INSERT INTO `vote-so`.`votes` (`voter_name`, `voter_email`, `voter_gender`, `voter_age`, `voter_phone`, `candidate_id`, `voter_comment`) VALUES ('Waris', 'abc3@gmail.com', 'Male', '25', '033312005331', '15', 'Very good');
INSERT INTO `vote-so`.`votes` (`voter_name`, `voter_email`, `voter_gender`, `voter_age`, `voter_phone`, `candidate_id`, `voter_comment`) VALUES ('Waris', 'abc3@gmail.com', 'Male', '25', '033412005331', '16', 'Very good');
INSERT INTO `vote-so`.`votes` (`voter_name`, `voter_email`, `voter_gender`, `voter_age`, `voter_phone`, `candidate_id`, `voter_comment`) VALUES ('Waris', 'abc@4gmail.com', 'Male', '25', '033152005331', '17', 'Very good');
INSERT INTO `vote-so`.`votes` (`voter_name`, `voter_email`, `voter_gender`, `voter_age`, `voter_phone`, `candidate_id`, `voter_comment`) VALUES ('Waris', 'abc@g5mail.com', 'Male', '25', '033126005331', '18', 'Very good');
INSERT INTO `vote-so`.`votes` (`voter_name`, `voter_email`, `voter_gender`, `voter_age`, `voter_phone`, `candidate_id`, `voter_comment`) VALUES ('Waris', 'abc@gm6ail.com', 'Male', '25', '033120705331', '19', 'Very good');
INSERT INTO `vote-so`.`votes` (`voter_name`, `voter_email`, `voter_gender`, `voter_age`, `voter_phone`, `candidate_id`, `voter_comment`) VALUES ('Waris', 'abc@gma7il.com', 'Male', '25', '033120085331', '20', 'Very good');
INSERT INTO `vote-so`.`votes` (`voter_name`, `voter_email`, `voter_gender`, `voter_age`, `voter_phone`, `candidate_id`, `voter_comment`) VALUES ('Waris', 'abc@gmai8l.com', 'Male', '25', '0331200590331', '21', 'Very good');
INSERT INTO `vote-so`.`votes` (`voter_name`, `voter_email`, `voter_gender`, `voter_age`, `voter_phone`, `candidate_id`, `voter_comment`) VALUES ('Waris', 'abc@gmail9.com', 'Male', '25', '033120053311', '22', 'Very good');
INSERT INTO `vote-so`.`votes` (`voter_name`, `voter_email`, `voter_gender`, `voter_age`, `voter_phone`, `candidate_id`, `voter_comment`) VALUES ('Waris', 'abc@gmail.0com', 'Male', '25', '0331200533132', '23', 'Very good');
INSERT INTO `vote-so`.`votes` (`voter_name`, `voter_email`, `voter_gender`, `voter_age`, `voter_phone`, `candidate_id`, `voter_comment`) VALUES ('Waris', 'abc@gmail.c0om', 'Male', '25', '003312005331', '24', 'Very good');
INSERT INTO `vote-so`.`votes` (`voter_name`, `voter_email`, `voter_gender`, `voter_age`, `voter_phone`, `candidate_id`, `voter_comment`) VALUES ('Waris', 'abc@gmail.co0m', 'Male', '25', '093312005331', '12', 'Very good');
INSERT INTO `vote-so`.`votes` (`voter_name`, `voter_email`, `voter_gender`, `voter_age`, `voter_phone`, `candidate_id`, `voter_comment`) VALUES ('Waris', 'abc@gmail.com0', 'Male', '25', '038312005331', '13', 'Very good');
INSERT INTO `vote-so`.`votes` (`voter_name`, `voter_email`, `voter_gender`, `voter_age`, `voter_phone`, `candidate_id`, `voter_comment`) VALUES ('Waris', '1abc@gmail.com', 'Male', '25', '033712005331', '14', 'Very good');
INSERT INTO `vote-so`.`votes` (`voter_name`, `voter_email`, `voter_gender`, `voter_age`, `voter_phone`, `candidate_id`, `voter_comment`) VALUES ('Waris', 'a3bc@gmail.com', 'Male', '25', '033162005331', '18', 'Very good');
INSERT INTO `vote-so`.`votes` (`voter_name`, `voter_email`, `voter_gender`, `voter_age`, `voter_phone`, `candidate_id`, `voter_comment`) VALUES ('Waris', 'ab4c@gmail.com', 'Male', '25', '033125005331', '13', 'Very good');
INSERT INTO `vote-so`.`votes` (`voter_name`, `voter_email`, `voter_gender`, `voter_age`, `voter_phone`, `candidate_id`, `voter_comment`) VALUES ('Waris', 'abc5@gmail.com', 'Male', '25', '033120405331', '12', 'Very good');
INSERT INTO `vote-so`.`votes` (`voter_name`, `voter_email`, `voter_gender`, `voter_age`, `voter_phone`, `candidate_id`, `voter_comment`) VALUES ('Waris', 'abc@6gmail.com', 'Male', '25', '033120035331', '17', 'Very good');
